runtime: python
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/sample-cloud-app/index.html
  upload: dist/sample-cloud-app/index.html
- url: /
  static_dir: dist/sample-cloud-app